add <SiteTour> component
Audentio/components pull request #104
Opened 2021-07-01 02:00 UTC by grantrygh

2021-07-02 20:48 UTC, tushar-singh requested changes

2021-07-02 20:48 UTC, tushar-singh commented on src/Table/components/Td/Td.tsx
> +export const CriticalActionsTd = ({ actions, mobileMenu, mobileMenuIcon, ...props }: CriticalActionsTdProps) => {
since this is a separate component almost, it should be separated out. Otherwise we add deadweight code to projects using just the table Td and not this component

2021-07-02 22:35 UTC, grantrygh commented
@tushar-singh thanks, separated that out, should be good

2021-07-05 16:48 UTC, tushar-singh approved these changes

2021-07-05 16:48 UTC, merged