refactor: modal refactor, fixes, remove react-spring, update transitions
Audentio/components pull request #84
Opened 2021-06-10 22:37 UTC by grantrygh

2021-06-10 23:59 UTC, tushar-singh requested changes

2021-06-10 23:59 UTC, tushar-singh commented on src/Modal/useIds.ts
> +// This implementation is heavily inspired by react-aria's implementation
@grantrygh this seems like a global utility as opposed to being Modal specific. Likely other chakra components we import might use this as well

2021-06-11 00:11 UTC, grantrygh commented on src/Modal/useIds.ts
> +// This implementation is heavily inspired by react-aria's implementation
good point. updated

2021-06-12 00:54 UTC, tushar-singh approved these changes

2021-06-12 00:54 UTC, merged