fixes
Audentio/components pull request #99
Opened 2021-06-23 21:44 UTC by grantrygh

timestamp component, updates for simplied graph version, cssreset fix

2021-06-23 23:27 UTC, tushar-singh requested changes

2021-06-23 23:27 UTC, tushar-singh commented on src/CSSReset/CSSReset.tsx
> +                ${!noHeight && 'height: 100%;'}
lol thanks for fixing that

2021-06-23 23:27 UTC, tushar-singh commented on src/CountdownTimer/CountdownTimer.tsx
> +            setInterval(() => {
needs effect cleanup 

```
let counter: number;
if (days === 0) {
            counter = setInterval(() => {
....

// cleanup
return () => clearInterval(counter)
```

2021-06-23 23:27 UTC, tushar-singh commented on src/CountdownTimer/CountdownTimer.tsx
> +    if (num > 9) {
there's a better way. Strings have a `padStart()` method

```
const numString = Math.abs(passedNum).toString();

return numString.padStart(2, '0');
```

2021-06-23 23:27 UTC, tushar-singh commented on src/CountdownTimer/CountdownTimer.tsx
> +function useInitialDiff(to: Date | string) {
only use `useX` pattern for naming hooks. This is a pure function so this should be named `getInitialDiff`

2021-06-23 23:27 UTC, tushar-singh commented on src/CountdownTimer/CountdownTimer.tsx
> +                const $hours = Math.floor(secondsToStart / 3600);
Instead of doing this calc yourself you can use date-fns.
_note: import the functions separately. I just used `dateFns.fn` for clarity_

```
const diffInSeconds = differenceInSeconds(countdownTime, currentTime);
const secondsToStart = dateFns.addSeconds(new Date(), diffInSeconds)
const formattedDuration = dateFns.format(helperDate, 'hh:mm:ss');
```

then you can just set formattedDuration in state and use that in render.

2021-06-23 23:27 UTC, tushar-singh commented on src/CountdownTimer/types.ts
> +    start_at: Date;
date from API will be a string. so let's support both strings and Date
Ideally we pass strings and the component can do conversion (and memoization if needed)

2021-06-23 23:27 UTC, tushar-singh commented on src/Graph/Graph.tsx
> +                {!basic && <XAxis dataKey="name" {...axisStyleProps} />}
can use fragment here for single condition

2021-06-23 23:27 UTC, tushar-singh commented on src/Timestamp/getFormattedOffset.ts
> +        const hours = Math.floor(-d.getTimezoneOffset() / 60);
let's do the same thing mentioned above here, with date-fns.

2021-06-24 01:02 UTC, grantrygh commented on src/CountdownTimer/CountdownTimer.tsx
> +    if (num > 9) {
ah, didn't know about this. cool

2021-06-24 01:05 UTC, grantrygh commented on src/Timestamp/getFormattedOffset.ts
> +        const hours = Math.floor(-d.getTimezoneOffset() / 60);
is using date-fns needed here?

this is just dealing with a static minutes value based on the offset, rather than the date itself.

2021-06-24 01:08 UTC, grantrygh commented on src/CountdownTimer/CountdownTimer.tsx
> +                const $hours = Math.floor(secondsToStart / 3600);
lmk thoughts on this solution instead : https://stackoverflow.com/questions/1322732/convert-seconds-to-hh-mm-ss-with-javascript

don't believe the countdown will ever have a formatting different than hh:mm:ss returned by that and don't have to deal with converting timezones

2021-06-24 01:14 UTC, tushar-singh commented on src/CountdownTimer/CountdownTimer.tsx
> +                const $hours = Math.floor(secondsToStart / 3600);
yeah that seems fine as well

2021-06-24 01:20 UTC, tushar-singh approved these changes

2021-06-24 01:20 UTC, tushar-singh commented on src/Timestamp/getFormattedOffset.ts
> +        const hours = Math.floor(-d.getTimezoneOffset() / 60);
no but if we're doing essentially the same thing and already bundle date-fns, might as well use their battle tested and maintained code - perhaps there are edge cases we'll miss but date-fns won't
date-fns can also do this same thing without needing a date. offset works just fine

2021-06-24 01:21 UTC, merged